version: 2.1
jobs:
  build:
    executor:
      name: node/default
      tag: "12.19.0"
    steps:
      - checkout
      - node/install-packages
      - run: npm run test
      - run: npm run build
orbs:
  node: circleci/node@4.1.0
workflows:
  test-and-deploy:
    jobs:
      - build
